version: '3.7'
services:
  postgres:
    build: ./postgres
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ososystem:
    build: .
    depends_on:
      - postgres
    networks:
      - backend

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - type: bind
        source: ./oso-realm.json
        target: /tmp/oso-realm.json

networks:
  backend:
    driver: bridge